### ISSUE TITLE
Version for 1.5.0-rc.4 don't show in UI

### ISSUE THREAD

**Issue by ghost** [MeteorPackaging/autopublish.meteor.com#13]
The version of the release in the screenshot is 1.5.0-rc.4.

![bildschirmfoto 2015-04-03 um 14 46 56](https://cloud.githubusercontent.com/assets/727955/6982312/6a4bfa06-da10-11e4-8ec3-484ad21f845e.png)

**Comment by splendido** [comment]
Checking this right now...

**Comment by splendido** [comment]
I might have had a little bug inside the regexp I use to verify the published version from the log: see 8bdcc2cbcb57042e1848d96cf09277903c42261e

see also [this test](https://regex101.com/r/iW0tD2/1)

likely, I still have to solve how to clean up all the log lines starting with `\r` used by meteor to update the log keeping the cursor on the very same line... :(
See [this method](https://github.com/MeteorPackaging/autopublish.meteor.com/blob/cd61e543d527737871358c8106f17a91a58d56ee/server/lib/workflows/host.js#L56-63) I use internally to finally _compress_ the log.

...even if this is what I got as final log:

```
meteor publish\rkarma-chrome-launcher, karma-firefox-launcher, karma-jasmine,\nkarma-coffee-preprocessor, karma-phantomjs-launcher, karma-sauce-launcher,\nfs-extra...
```

and I see the connection to the build machine had a timeout :(
could you confirm the package was actually published?

I'm going to re-trigger the publish manually, to see if this time the operation succeeds!

**Comment by ghost** [comment]
Oops, it hasn't been published.

```
Jonas-MBP:Projects jonas$ meteor show sanjo:karma@1.5.0-rc.4 --ejson
sanjo:karma@1.5.0-rc.4: not found
```

**Comment by splendido** [comment]
I've just discovered Meteor@1.1.0.1 was released and the build machine had a timeout trying to update the meteor version...
I still have not figured out why this is happening all the times they release a new version :(

Now I've updated Meteor and the log I get is still:

```
meteor publish\rkarma-chrome-launcher, karma-firefox-launcher, karma-jasmine,\nkarma-coffee-preprocessor, karma-phantomjs-launcher, karma-sauce-launcher,\nfs-extra...\rdescription\nnpm WARN package.json packages-for-meteor-smartpackage-1kqwn16@0.0.0 No\nrepository field.\nnpm WARN package.json packages-for-meteor-smartpackage-1kqwn16@0.0.0 No README\ndata\rWhile building package sanjo:karma:\nerror: couldn't install npm packages from npm-shrinkwrap
```

**Comment by splendido** [comment]
I'll try to switch to an official meteor build machine...

**Comment by ghost** [comment]
I've tried `meteor publish` and deleted .npm/packages/node_modules before and it worked.
I think in your log is the stderr missing. This is what I got locally earlier:

```
Jonas-MBP:karma jonas$ meteor publish                                                                                                                                        
sanjo:karma: updating npm dependencies -- chokidar, karma, karma-chrome-launcher, karma-firefox-launcher, karma-jasmine, karma-coffee-preprocessor,
karma-phantomjs-launcher, karma-sauce-launcher, fs-extra...
npm WARN package.json packages-for-meteor-smartpackage-o51xm2@0.0.0 No description
npm WARN package.json packages-for-meteor-smartpackage-o51xm2@0.0.0 No repository field.
npm WARN package.json packages-for-meteor-smartpackage-o51xm2@0.0.0 No README data
npm ERR! Error: version not found: i@0.3.2
npm ERR!     at
/Users/jonas/.meteor/packages/meteor-tool/.1.1.2.leddhq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/lib/cache/add-named.js:125:12
npm ERR!     at saved
(/Users/jonas/.meteor/packages/meteor-tool/.1.1.2.leddhq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at Object.oncomplete (fs.js:108:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 14.1.0
npm ERR! command "/Users/jonas/.meteor/packages/meteor-tool/.1.1.2.leddhq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/jonas/.meteor/packages/meteor-tool/.1.1.2.leddhq++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm" "install"
npm ERR! cwd /Users/jonas/Projects/karma/.npm/package-new-1h33abg
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0

=> Errors while initializing project:         

While building package sanjo:karma:
error: couldn't install npm packages from npm-shrinkwrap
```

I will push a new rc so you can test it.

**Comment by splendido** [comment]
mmm, let me a few more minutes...
I can easily re-trigger the latest one!

**Comment by ghost** [comment]
I pushed 1.5.0-rc.5. It's unpublished. You can use this one to test.

**Comment by splendido** [comment]
Ok, thanks!

if you see it under the _queueing_ list again you know why ;-)

**Comment by splendido** [comment]
On the official meteor build machine I got a `ENOMEM` error a couple of time... :(
But I'm still getting the same error without managing to add the _stderr_ log to the _stdout_ log

**Comment by splendido** [comment]
@Sanjo I've just added a page to see the log for failed publish operations.
Hope it might help in the future!

**Comment by splendido** [comment]
The official build machine has much more memory...
Should be better now.

But still I have some doubts about the ssh connection I'm using :(

Btw, I'm closing this here for now
